In [3]:
import numpy as np
c=np.array([[[2,4,6,8],[10,12,14,16],[18,20,22,24]]])
print("Three dimensional array:\n",c)
d=np.zeros((3,4))
print("Array with all zeros:\n",d)
e=np.array([5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
slice1=e[::2]
print("Sliced array with step 2:",slice1)
print("\nShape of the array:",slice1.shape)
print("\nDimension of the array:",slice1.ndim)
print("\nArray element type:",slice1.dtype)
FA=slice1.flatten()
print("\nFLattened array:",FA)

Three dimensional array:
 [[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]]
Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Sliced array with step 2: [ 5  7  9 11 13 15 17 19 21 23 25 27 29]

Shape of the array: (13,)

Dimension of the array: 1

Array element type: int64

FLattened array: [ 5  7  9 11 13 15 17 19 21 23 25 27 29]
