In [1]:
import numpy as np
a=np.array([1,2,3,4])
print("One dimensional array:",a)


One dimensional array: [1 2 3 4]


In [6]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print("Two dimensional array:\n",b)


Two dimensional array:
 [[1 2 3 4]
 [5 6 7 8]]


In [5]:
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print("Three dimensional array:\n",c)


Three dimensional array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [7]:
import numpy as np
d=np.zeros((4,4))
print("Array with all zeros:\n",d)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
import numpy as np
e=np.random.random((2,3))
print("\n Random value:\n",e)


 Random value:
 [[0.55245709 0.54046061 0.8550559 ]
 [0.40085892 0.49100352 0.35348427]]


In [12]:
import numpy as np
f=np.arange(0,200,40)
print("\n Sequence array:\n",f)


 Sequence array:
 [  0  40  80 120 160]


In [14]:
import numpy as np
g=np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
newarr=g.reshape(4,3)
print("\n Original array:\n",g)
print("\n Reshaped array:\n",newarr)


 Original array:
 [[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]

 Reshaped array:
 [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [16]:
import numpy as np
h=np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
newarr=h.flatten()
print("\n Original array:\n",h)
print("\n Flattened array:\n",newarr)


 Original array:
 [[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]

 Flattened array:
 [11 12 13 14 15 16 17 18 19 20 21 22]


In [7]:
import numpy as np
i=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print("Three dimensional array:\n",i)
print("\n No. of dimensions:",i.ndim)

Three dimensional array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

 No. of dimensions: 2


In [8]:
import numpy as np
j=np.array([[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print("Three dimensional array:\n",j)
print("\n No. of dimensions:",j.ndim)

Three dimensional array:
 [[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

 No. of dimensions: 3


In [11]:
import numpy as np
k=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print("Three dimensional array:\n",k)
print("\n Shape of the array:",k.shape)

Three dimensional array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

 Shape of the array: (3, 4)


In [14]:
import numpy as np
l=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print("Three dimensional array:\n",l)
print("\n Array element type:\n",l.dtype)

Three dimensional array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

 Array element type:
 int64


In [17]:
import numpy as np
m=np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
size=len(m[1])
print("Three dimensional array:\n",l)
print("\n Size of array:",size)

Three dimensional array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

 Size of array: 4


In [6]:
import numpy as np
n=[1,2,3]
n=np.array(n)
newtype = n.astype('float64')
print("Original array:",n)
print("New array:",newtype)
print(newtype.dtype)

Original array: [1 2 3]
New array: [1. 2. 3.]
float64
