In [1]:
#Slicing array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
#slice the index from 2 to 5
slice1=a[2:5]
print("Original array:",a)
print("Sliced array",slice1)

Original array: [1 2 3 4 5 6 7 8 9]
Sliced array [3 4 5]


In [7]:
#Slicing with step
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9])
slice2=b[::2]
print("Original array:",b)
print("Sliced array with step 2:",slice2)

Original array: [1 2 3 4 5 6 7 8 9]
Sliced array with step 2: [1 3 5 7 9]


In [8]:
#Reversal 
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9])
revarr=c[::-1]
print("Original array:",c)
print("Reversed array:",revarr)

Original array: [1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1]


In [12]:
#Sub array rows
import numpy as np
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=d[0:2,1:3]
print("Original array:\n",d)
print("Sub array:\n",subarr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub array:
 [[2 3]
 [5 6]]


In [14]:
#Extraction element
import numpy as np
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=e[:2,:1]
print("Original array:\n",e)
print("Sub array:\n",subarr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub array:
 [[1]
 [4]]


In [16]:
#Extraction column
import numpy as np
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=f[:,0]
print("Original array:\n",f)
print("Sub array:\n",subarr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub array:
 [1 4 7]


In [17]:
#Extraction row
import numpy as np
g=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=g[0,:]
print("Original array:\n",g)
print("Sub array:\n",subarr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub array:
 [1 2 3]


In [18]:
#Extraction two rows
import numpy as np
h=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=h[0:2:1]
print("Original array:\n",h)
print("Sub array:\n",subarr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub array:
 [[1 2 3]
 [4 5 6]]


In [31]:
#Array indexing 
import numpy as np
import array
i=array.array('i',[10,20,30,40,50])
print("Element1:",i[0])
print("Element2:",i[3])

Element1: 10
Element2: 40


In [32]:
#Array indexing 
import numpy as np
j=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Element1:",j[0,0])
print("Element2:",j[2,1])

Element1: 1
Element2: 8


In [35]:
#Basic indexing
import numpy as np
j1=np.array([1,2,3,4,5,6,7,8,9])
print("Sub array:",j1[0:5])

Sub array: [1 2 3 4 5]


In [14]:
#Negative indexing
import numpy as np
j2=np.array([1,2,3,4,5,6,7,8,9])
print("Sub array:",j2[0:-3])

Sub array: [1 2 3 4 5 6]


In [36]:
#Slicing indexing
import numpy as np
j3=np.array([1,2,3,4,5,6,7,8,9])
print("Sub array:",j3[j3>5])

Sub array: [6 7 8 9]


In [5]:
#Fancy indexing
import numpy as np
j4=np.array([1,2,3,4,5,6,7,8,9])
print("Fancy indexing:",j4[[1,3]])

Fancy indexing: [2 4]


In [15]:
#Horizontal join
import numpy as np
l1=np.array([[1,2],[3,4]])
l2=np.array([[5,6],[7,8]])
l1array=np.hstack((l1,l2))
print(resarray)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [16]:
#Vertical join
import numpy as np
l1=np.array([[1,2],[3,4]])
l2=np.array([[5,6],[7,8]])
l2array=np.vstack((l1,l2))
print(resarray)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [13]:
#Depth join
import numpy as np
l1=np.array([[1,2],[3,4]])
l2=np.array([[5,6],[7,8]])
l3array=np.dstack((l1,l2))
print(resarray)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [19]:
#Splitting of array
import numpy as np
m=np.array([1,2,3,4,5,6])
marray=np.split(m,3)
print(marray)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
#Splitting of array
import numpy as np
m=np.array([1,2,3,4,5])
marray=np.array_split(m,3)
print(marray)

[array([1, 2]), array([3, 4]), array([5])]
